### ISSUE TITLE
Phoenix >= 1.4.7 does not generate routes

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet#469]
https://github.com/xerions/phoenix_swagger/issues/232

Waiting for new version of phoenix_swagger

**Comment by Aulud** [comment]
@geshuming Hmm, appears the issue is fixed in `master` of phoenix_swagger, but it seems there haven't been any new versions of phoenix_swagger published in Hex since July 2018. It's possible the original repo owner is no longer working on it. Should we consider pulling the dependency directly from the GitHub repo?

Source: https://github.com/api-hogs/bureaucrat/issues/50#issuecomment-517347660

**Comment by ijunaid8989** [comment]
While using the master branch I am still getting an error as
```
** (Poison.EncodeError) unable to encode value: {:required, true}
    lib/poison/encoder.ex:383: Poison.Encoder.Any.encode/2
    lib/poison/encoder.ex:268: anonymous fn/4 in Poison.Encoder.List.encode/3
    lib/poison/encoder.ex:269: Poison.Encoder.List.encode/3
    lib/poison/encoder.ex:221: anonymous fn/5 in Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map."-encode/3-lists^foldl/2-1-"/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:268: anonymous fn/4 in Poison.Encoder.List.encode/3
    lib/poison/encoder.ex:269: Poison.Encoder.List.encode/3
    lib/poison/encoder.ex:221: anonymous fn/5 in Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map."-encode/3-lists^foldl/2-1-"/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:221: anonymous fn/5 in Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map."-encode/3-lists^foldl/2-1-"/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:221: anonymous fn/5 in Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map."-encode/3-lists^foldl/2-1-"/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:221: anonymous fn/5 in Poison.Encoder.Map.encode/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map."-encode/3-lists^foldl/2-1-"/3
    lib/poison/encoder.ex:222: Poison.Encoder.Map.encode/3
```

**Comment by jangnezda** [comment]
@ijunaid8989 I haven't seen that when testing with master branch, but I'm not using Poison encoder in my projects. This is in my config:

```elixir
config :phoenix_swagger, :json_library, Jason
```

**Comment by jiachen247** [comment]
18:01:25.665 [warn]  Failed to generate priv/static/swagger.json: Failed to load module: Elixir.CadetWeb.Router: nofile

**Comment by jiachen247** [comment]
any updates with regards to this?

**Comment by angelsl** [comment]
Fixed in 621cab70ccd914f48fbbd824f62bcdb1393a1308.
